# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/OmerFarukPC/Desktop/Ders/vivado_projects/AES_TEST_1/AES_TEST_1.srcs/sources_1/bd/rcon_LUT/ip/rcon_LUT_blk_mem_gen_0_0/rcon_LUT_blk_mem_gen_0_0.xci
# IP: The module: 'rcon_LUT_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OmerFarukPC/Desktop/Ders/vivado_projects/AES_TEST_1/AES_TEST_1.srcs/sources_1/bd/rcon_LUT/ip/rcon_LUT_blk_mem_gen_0_0/rcon_LUT_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rcon_LUT_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/OmerFarukPC/Desktop/Ders/vivado_projects/AES_TEST_1/AES_TEST_1.srcs/sources_1/bd/rcon_LUT/ip/rcon_LUT_blk_mem_gen_0_0/rcon_LUT_blk_mem_gen_0_0.xci
# IP: The module: 'rcon_LUT_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OmerFarukPC/Desktop/Ders/vivado_projects/AES_TEST_1/AES_TEST_1.srcs/sources_1/bd/rcon_LUT/ip/rcon_LUT_blk_mem_gen_0_0/rcon_LUT_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rcon_LUT_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
