# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/rcon_LUT/rcon_LUT.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rcon_LUT || ORIG_REF_NAME==rcon_LUT} -quiet] -quiet

# IP: bd/rcon_LUT/ip/rcon_LUT_blk_mem_gen_0_0/rcon_LUT_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rcon_LUT_blk_mem_gen_0_0 || ORIG_REF_NAME==rcon_LUT_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/gf_mul_3_LUT/gf_mul_3_LUT.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gf_mul_3_LUT || ORIG_REF_NAME==gf_mul_3_LUT} -quiet] -quiet

# IP: bd/gf_mul_3_LUT/ip/gf_mul_3_LUT_blk_mem_gen_0_0/gf_mul_3_LUT_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gf_mul_3_LUT_blk_mem_gen_0_0 || ORIG_REF_NAME==gf_mul_3_LUT_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/gf_mul_2_LUT/gf_mul_2_LUT.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gf_mul_2_LUT || ORIG_REF_NAME==gf_mul_2_LUT} -quiet] -quiet

# IP: bd/gf_mul_2_LUT/ip/gf_mul_2_LUT_blk_mem_gen_0_0/gf_mul_2_LUT_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gf_mul_2_LUT_blk_mem_gen_0_0 || ORIG_REF_NAME==gf_mul_2_LUT_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/rcon_LUT/rcon_LUT_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc

# XDC: bd/gf_mul_3_LUT/gf_mul_3_LUT_ooc.xdc

# XDC: bd/gf_mul_2_LUT/gf_mul_2_LUT_ooc.xdc
